### ISSUE TITLE
Void stone option randomly "turns off"

### ISSUE THREAD

**Issue by tgkgate** [Allen-Wrench/AutoRemoveStone#3]
For reasons I cannot explain,  the Void Stone option on my drills turns itself off.   which is kinda frustrating on remote mining outposts.   

I can find no error message,  exceptions, or anything odd in the logs.   So unfortunately i don't have much of a "bug" report.   Is this intended behavior?

**Comment by tgkgate** [comment]
Addendum

It seems to be tied into leaving a control seat.   (any control seat,  cockpit, etc).

**Comment by Allen-Wrench** [comment]
Yeah it's designed to stop voiding if you leave the control seat.

**Comment by Squeech007** [comment]
can you make this into a toggle? thinking about autominers... @.@
