### ISSUE TITLE
Void stone removes Ingot:Stone (Gravel)

### ISSUE THREAD

**Issue by tgkgate** [Allen-Wrench/AutoRemoveStone#4]
The option to void stone delete gravel too

**Comment by Allen-Wrench** [comment]
I see, the plugin uses the word "stone" to decide what item to void, so that's a possibility. I've never had gravel on my mining ships so it was never an issue. It should be fairly simple to prevent that from happening though. I'll see what I can do.

**Comment by Allen-Wrench** [comment]
Should be fixed next time the plugin list updates, thanks for the heads up!
